language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
install:
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov
